config/routes.rb
# Calendar Importer - plugin for redmine project management software
# Copyright (C) 2007-2012  Blend Interactive
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


RedmineApp::Application.routes.draw do
  match 'calendar_import/:name' => 'calendar_imports#user_index'
  match 'calendar_import/:name/pull' => 'calendar_imports#user_pull'
  match 'calendar_import' => 'calendar_imports#index'
  
  match 'user_calendars/show/:id' => 'user_calendars#show', :as => "show_user_calendar", :via => :get
  match 'skipped_entries/show/:id' => 'skipped_entries#show', :as => "show_skipped_entries", :via => :get  
  
  resources :user_calendars
  resources :user_to_project_mappings
  resources :event_to_issue_errors
  #resources :skipped_entries
end

app/models/user_to_project_mapping.rb
# Calendar Importer - plugin for redmine project management software
# Copyright (C) 2007-2012  Blend Interactive
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class UserToProjectMapping < ActiveRecord::Base
    belongs_to :user
    belongs_to :project
    validates_presence_of :project_id, :project_alias 

    validates_uniqueness_of :project_alias, :scope=> :user_id, :message=> 'must be unique.  You have already used this Project Alias.  Either pick a new one or go back and remove your previous project alias.'
end

app/controllers/user_to_project_mappings_controller.rb
# Calendar Importer - plugin for redmine project management software
# Copyright (C) 2007-2012  Blend Interactive
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class UserToProjectMappingsController < ApplicationController
  unloadable
  layout 'base'

  # GET /user_to_project_mappings
  # GET /user_to_project_mappings.xml
  def index
    @user_to_project_mappings = UserToProjectMapping.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @user_to_project_mappings }
    end
  end

  # GET /user_to_project_mappings/1
  # GET /user_to_project_mappings/1.xml
  def show
    @user_to_project_mapping = UserToProjectMapping.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user_to_project_mapping }
    end
  end

  # GET /user_to_project_mappings/new
  # GET /user_to_project_mappings/new.xml
  def new
    @projects = {}
    @projects_objects = Project.find(:all, :order=>"name")

    for @project_object in @projects_objects
        @projects[@project_object.name] = @project_object.id
    end
    
    @projects = @projects.sort()

    @user_to_project_mapping = UserToProjectMapping.new
    if params[:summary]
        @user_to_project_mapping.project_alias = params[:summary]
    end
    if params[:event_guid]
        @user_to_project_mapping.event_guid = params[:event_guid]
    end
    

    @user = User.current
    @user_to_project_mapping.user_id = @user.id

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user_to_project_mapping }
    end
  end

  # GET /user_to_project_mappings/1/edit
  def edit
    @user_to_project_mapping = UserToProjectMapping.find(params[:id])

    if params[:event_guid]
        @user_to_project_mapping.event_guid = params[:event_guid]
    end

    @projects = Project.find(:all, :order=>"name")
    @selected_project = Project.find(@user_to_project_mapping.project_id).name
  end

  # POST /user_to_project_mappings
  # POST /user_to_project_mappings.xml
  def create
    @user_to_project_mapping = UserToProjectMapping.new(params[:user_to_project_mapping])

    if params[:use_alias] == 'for all time entries.'
        @user_to_project_mapping.event_guid = '';
    end

    @user_to_project_mapping.project_id = params[:project]
    respond_to do |format|
      if @user_to_project_mapping.save
        @name = @user_to_project_mapping.project_alias
        flash[:notice] = "The project alias '#{@name}' was successfully created."
        format.html { redirect_to(url_for :controller => "calendar_imports", :action => "index") }

      else
        @projects = {}
        @projects_objects = Project.find(:all, :order=>"name")

        for @project_object in @projects_objects
            @projects[@project_object.name] = @project_object.id
        end
        
        @projects = @projects.sort()
        format.html { render :action => "new", :event_guid => @user_to_project_mapping.event_guid, :summary => @user_to_project_mapping.project_alias }
        format.xml  { render :xml => @user_to_project_mapping.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /user_to_project_mappings/1
  # PUT /user_to_project_mappings/1.xml
  def update
    @user_to_project_mapping = UserToProjectMapping.find(params[:id])
        
    if params[:use_alias] == 'for all time entries.'
        @user_to_project_mapping.event_guid = '';
    end

    respond_to do |format|
      if @user_to_project_mapping.update_attributes(params[:user_to_project_mapping])
        flash[:notice] = "'#{@user_to_project_mapping.project_alias}' was successfully updated."
        format.html { redirect_to(url_for :controller => "calendar_imports", :action => "index") }
        format.xml  { head :ok }
      else
        @projects = Project.find(:all, :order=>"name")
        @selected_project = Project.find(@user_to_project_mapping.project_id).name #declared here for render "edit" to display selected_project.name
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user_to_project_mapping.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_to_project_mappings/1
  # DELETE /user_to_project_mappings/1.xml
  def destroy
    @user_to_project_mapping = UserToProjectMapping.find(params[:id])
    @name = @user_to_project_mapping.project_alias
    @user_to_project_mapping.destroy

    respond_to do |format|
      flash[:notice] = "The project alias '#{@name}' was successfully removed."
      format.html { redirect_to(url_for :controller => "calendar_imports", :action => "index") }
      format.xml  { head :ok }
    end
  end
end

app/views/user_to_project_mappings/edit.html.erb
<h1>Editing Project Alias for <%= @selected_project %></h1>

<%= error_messages_for @user_to_project_mapping %>

<br />
<%= form_for(@user_to_project_mapping) do |f| %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :event_guid %>
    <%= f.hidden_field :project_id %>


  <p>
    <b>Project alias</b><br />
    <%= f.text_field :project_alias, :autofocus => true %>
  </p>

   <% if FALSE %>
  <p>
    <b>Use this alias...</b>
    <%= select_tag "use_alias", options_for_select([[ "for all time entries.", 1], ["for only this one time entry.", 2]], 1) %>

  </p>
  <% end %>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Back', :controller=>'calendar_imports', :action=>'index' %>

app/views/user_to_project_mappings/index.html.erb
<h1>Listing user_to_project_mappings</h1>

<table>
  <tr>
    <th>User</th>
    <th>Project</th>
    <th>Project alias</th>
    <th>Event GUID</th>
  </tr>

<% for user_to_project_mapping in @user_to_project_mappings %>
  <tr>
    <td><%=h user_to_project_mapping.user_id %></td>
    <td><%=h user_to_project_mapping.project_id %></td>
    <td><%=h user_to_project_mapping.project_alias %></td>
    <td><%=h user_to_project_mapping.event_guid %></td>
    <td><%= link_to 'Show', user_to_project_mapping %></td>
    <td><%= link_to 'Edit', edit_user_to_project_mapping_path(user_to_project_mapping) %></td>
    <td><%= link_to 'Destroy', user_to_project_mapping, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New user_to_project_mapping', new_user_to_project_mapping_path %>

app/views/user_to_project_mappings/new.html.erb
<h1>New Project Alias</h1>
<br />

<%= error_messages_for @user_to_project_mapping %>

<%= form_for(@user_to_project_mapping) do |f| %>
  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :event_guid %>

  <b>Project Name</b><br />
  <%= select_tag 'project', options_for_select(@projects), :multiple => false, :size => 20 %>

  <p>
    <b>Project Alias</b><br />
    <%= f.text_field :project_alias %>
  </p>

    <% if @user_to_project_mapping.event_guid %>
      <p>
      <b>Use this alias...</b>

      <%= select_tag "use_alias", options_for_select([ "for all time entries.", "for only this one time entry."], "for all time entries.") %>


      </p>
    <% end %>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', :controller=>'calendar_imports', :action=>'index' %>

app/views/user_to_project_mappings/show.html.erb
<p>
  <b>User:</b>
  <%=h @user_to_project_mapping.user_id %>
</p>

<p>
  <b>Project:</b>
  <%=h @user_to_project_mapping.project_id %>
</p>

<p>
  <b>Project alias:</b>
  <%=h @user_to_project_mapping.project_alias %>
</p>

<p>
  <b>Event Guid:</b>
  <%=h @user_to_project_mapping.event_guid %>
</p>



<%= link_to 'Edit', edit_user_to_project_mapping_path(@user_to_project_mapping) %> |
<%= link_to 'Back', user_to_project_mappings_path %>