config/routes.rb
# Calendar Importer - plugin for redmine project management software
# Copyright (C) 2007-2012  Blend Interactive
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


RedmineApp::Application.routes.draw do
  match 'calendar_import/:name' => 'calendar_imports#user_index'
  match 'calendar_import/:name/pull' => 'calendar_imports#user_pull'
  match 'calendar_import' => 'calendar_imports#index'
  
  match 'user_calendars/show/:id' => 'user_calendars#show', :as => "show_user_calendar", :via => :get
  match 'skipped_entries/show/:id' => 'skipped_entries#show', :as => "show_skipped_entries", :via => :get  
  
  resources :user_calendars
  resources :user_to_project_mappings
  resources :event_to_issue_errors
  #resources :skipped_entries
end

app/models/event_to_issue_error.rb
# Calendar Importer - plugin for redmine project management software
# Copyright (C) 2007-2012  Blend Interactive
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class EventToIssueError < ActiveRecord::Base
    belongs_to :user
    belongs_to :error 
end

app/controllers/event_to_issue_errors_controller.rb
# Calendar Importer - plugin for redmine project management software
# Copyright (C) 2007-2012  Blend Interactive
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class EventToIssueErrorsController < ApplicationController
  unloadable
  layout 'base'
  before_filter :require_admin
  skip_before_filter :require_admin, :only => [:show]

  # GET /event_to_issue_errors
  # GET /event_to_issue_errors.xml
  def index
    @event_to_issue_errors = EventToIssueError.find(:all, :conditions => ["start_date > ?", 2.months.ago ])
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => EventToIssueError.find(:all) }
    end
  end

  # GET /event_to_issue_errors/1
  # GET /event_to_issue_errors/1.xml
  def show
    @event_to_issue_error = EventToIssueError.find(params[:id])
    @error_description = Error.find(@event_to_issue_error.error_id).description
=begin
    description = @event_to_issue_error.description

    start_location = description.rindex(@event_to_issue_error.issue_id)
    start = description.slice(0,start_location)

    after_start = description.slice(start_location)
    end_location = after_start.rindex('<br/>#')
    if end_location == 0
        close = '<span style="color:#550000;">'+after_start+'</span>'
    else
        close = '<span style="color:#550000;">'+after_start.slice(0,end_location)+'</span>'+after_start.slice(end_location)
    end
    


    description = start+close

=end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event_to_issue_error }
    end
  end

  # GET /event_to_issue_errors/new
  # GET /event_to_issue_errors/new.xml
  def new
    @event_to_issue_error = EventToIssueError.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event_to_issue_error }
    end
  end

  # GET /event_to_issue_errors/1/edit
  def edit
    @event_to_issue_error = EventToIssueError.find(params[:id])
  end

  # POST /event_to_issue_errors
  # POST /event_to_issue_errors.xml
  def create
    @event_to_issue_error = EventToIssueError.new(params[:event_to_issue_error])

    respond_to do |format|
      if @event_to_issue_error.save
        flash[:notice] = 'EventToIssueError was successfully created.'
        format.html { redirect_to(@event_to_issue_error) }
        format.xml  { render :xml => @event_to_issue_error, :status => :created, :location => @event_to_issue_error }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event_to_issue_error.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /event_to_issue_errors/1
  # PUT /event_to_issue_errors/1.xml
  def update
    @event_to_issue_error = EventToIssueError.find(params[:id])

    respond_to do |format|
      if @event_to_issue_error.update_attributes(params[:event_to_issue_error])
        flash[:notice] = 'EventToIssueError was successfully updated.'
        format.html { redirect_to(@event_to_issue_error) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event_to_issue_error.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /event_to_issue_errors/1
  # DELETE /event_to_issue_errors/1.xml
  def destroy
    @event_to_issue_error = EventToIssueError.find(params[:id])
    @event_to_issue_error.destroy

    respond_to do |format|
      format.html { redirect_to(event_to_issue_errors_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/event_to_issue_errors/_skipped_entries_list.html.erb
<% if skipped_entries.any? %>

<div class="flash error">You'll want to verify that none of these items will effect your billing.</div>
<h1>Events that weren't pulled into Redmine</h1>

<table>
  <tr>
    <th>User</th>
    <th>Project</th>
    <th>Start date</th>
    <th>Text that was skipped</th>
  </tr>

<% for skipped_entry in skipped_entries %>
  <tr>
    <td><%=h User.find(skipped_entry.user_id).firstname %></td>
    <td><%=h skipped_entry.summary %></td>
    <td><%=h skipped_entry.start_date %></td>
    <td><%=h skipped_entry.skipped_text %></td>
    <td><%= link_to 'Show', skipped_entry %></td>
  </tr>
<% end %>
</table>

<% else %>
<div class="flash notice">No Skipped Entries!</div>
<% end %>

app/views/event_to_issue_errors/edit.html.erb
<h1>Editing event_to_issue_error</h1>

<%= error_messages_for :event_to_issue_error %>

<% form_for(@event_to_issue_error) do |f| %>
  <p>
    <b>User</b><br />
    <%= f.text_field :user_id %>
  </p>

  <p>
    <b>Calendar</b><br />
    <%= f.text_field :calendar_id %>
  </p>

  <p>
    <b>Event guid</b><br />
    <%= f.text_field :event_guid %>
  </p>

  <p>
    <b>Start date</b><br />
    <%= f.date_select :start_date %>
  </p>

  <p>
    <b>End date</b><br />
    <%= f.date_select :end_date %>
  </p>

  <p>
    <b>Issue</b><br />
    <%= f.text_field :issue_id %>
  </p>

  <p>
    <b>Error</b><br />
    <%= f.text_field :error_id %>
  </p>

  <p>
    <b>Summary</b><br />
    <%= f.text_area :summary %>
  </p>

  <p>
    <b>Description</b><br />
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @event_to_issue_error %> |
<%= link_to 'Back', event_to_issue_errors_path %>

app/views/event_to_issue_errors/index.html.erb
<% if @event_to_issue_errors.any? %>
    <div class="flash error">You'll want to verify that none of these items will effect your billing.</div>

    <h1>Event Errors that need to be corrected</h1>

    <table>
      <tr>
        <th>User</th>
        <th>Project</th>
        <th>Start date</th>
        <th>Error</th>
      </tr>

    <% for event_to_issue_error in @event_to_issue_errors %>
      <tr>
        <td><%=h User.find(event_to_issue_error.user_id).firstname %></td>
        <td><%=h event_to_issue_error.summary %></td>
        <td><%=h event_to_issue_error.start_date %></td>
        <td><%=h Error.find(event_to_issue_error.error_id).description %></td>
        <td><%= link_to 'Show', event_to_issue_error %></td>
      </tr>
    <% end %>
    </table>

<% else %>
<div class="flash notice">No Event Errors!</div>
<% end %>
<br /><br />
<%= render :partial=>"skipped_entries_list", :locals=>{:skipped_entries=>SkippedEntry.find(:all, :conditions => ["start_date > ?", 2.months.ago ])} %>

app/views/event_to_issue_errors/new.html.erb
<h1>New event_to_issue_error</h1>

<%= error_messages_for :event_to_issue_error %>

<% form_for(@event_to_issue_error) do |f| %>
  <p>
    <b>User</b><br />
    <%= f.text_field :user_id %>
  </p>
  <p>
    <b>Calendar</b><br />
    <%= f.text_field :calendar_id %>
  </p>


  <p>
    <b>Event guid</b><br />
    <%= f.text_field :event_guid %>
  </p>

  <p>
    <b>Start date</b><br />
    <%= f.date_select :start_date %>
  </p>

  <p>
    <b>End date</b><br />
    <%= f.date_select :end_date %>
  </p>

  <p>
    <b>Issue</b><br />
    <%= f.text_field :issue_id %>
  </p>

  <p>
    <b>Error</b><br />
    <%= f.text_field :error_id %>
  </p>

  <p>
    <b>Summary</b><br />
    <%= f.text_area :summary %>
  </p>

  <p>
    <b>Description</b><br />
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', event_to_issue_errors_path %>

app/views/event_to_issue_errors/show.html.erb
<% %>
<h1>Entry Error Details</h1>
<p>
  <b>Calendar:</b>
  <%=h UserCalendar.find(@event_to_issue_error.calendar_id).name %>
</p>

<p>
  <b>Date:</b>
  <%=h @event_to_issue_error.start_date.strftime('%m-%d-%Y %I:%M:%S %p %Z') %>
</p>

<p>
  <b>Project:</b>
  <%=h @event_to_issue_error.summary %>
</p>

<p>
  <b>Issue:</b>
  <%=h @event_to_issue_error.issue_id %>
</p>

<p>
  <b>Time Entries:</b>
  <%=h @event_to_issue_error.description %>
</p>

<p>
  <b>Error:</b>
  <%=h @error_description %>
</p>

<div class="box">
    <h3>Options</h3>
    <% case @event_to_issue_error.error_id
       when 1%>
        <%= link_to 'Create a New Alias', new_user_to_project_mapping_path(:event_guid => @event_to_issue_error.event_guid, :summary => @event_to_issue_error.summary ) %>
    <% when 2 %>
        You will need to edit the entry on your calendar application.<br />
        <p>
        <b>Things to keep in mind:</b>
        <ul>
            <li>You may need to divide your issue id and comment by a space
                <ul>
                    <li><b>CORRECT:</b> #1234 comment goes here</li>
                    <li><b>WRONG:</b> #1234comment goes here</li>
                </ul>
            </li>
        </ul>
        </p>
        
    <% when 4 %>
        You should move all of the notes for this issue into the previous reference to this issue.<br />
        <p>
        <b>Things to keep in mind:</b>
        <ul>
            <li>You can only enter time once for the same issue id.</li>
            <li>You may have referenced the issue by ID in one row and then by Name in another.</li>
        </ul>
        </p>
    <% when 7  %>
        You will need to edit the entry on your calendar application.<br />
        Make sure it follows the structure #Title - Description<br />
        <p>
        <b>Things to keep in mind:</b>
        <ul>
            <li>Use a '-' to separate the Title and Description</li>
            <li>Title and Description are required.</li>
        </ul>
        </p>
    <% when 10 %>
        You will need to edit the entry on your calendar application.<br />
        Make sure it follows the structure #Title - Description<br />
        <p>
        <b>Things to keep in mind:</b>
        <ul>
            <li>Use a '-' to separate the Title and Description</li>
            <li>Title and Description are required.</li>
        </ul>
        </p>
    <% else %>
        You will need to edit the entry on your calendar application.
    <% end %>
</div>

<%= link_to 'Back', :controller=>'calendar_imports', :action=>'index' %>