config/routes.rb
# Calendar Importer - plugin for redmine project management software
# Copyright (C) 2007-2012  Blend Interactive
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


RedmineApp::Application.routes.draw do
  match 'calendar_import/:name' => 'calendar_imports#user_index'
  match 'calendar_import/:name/pull' => 'calendar_imports#user_pull'
  match 'calendar_import' => 'calendar_imports#index'
  
  match 'user_calendars/show/:id' => 'user_calendars#show', :as => "show_user_calendar", :via => :get
  match 'skipped_entries/show/:id' => 'skipped_entries#show', :as => "show_skipped_entries", :via => :get  
  
  resources :user_calendars
  resources :user_to_project_mappings
  resources :event_to_issue_errors
  #resources :skipped_entries
end

app/models/user_calendar.rb
# Calendar Importer - plugin for redmine project management software
# Copyright (C) 2007-2012  Blend Interactive
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class UserCalendar < ActiveRecord::Base
    belongs_to :user
    validates_presence_of :user_id
    validates_presence_of :name, :message => ': Calendar name cannot be blank'
    validates_presence_of :ics_file, :message => ': An ics file must be given'
    validates_uniqueness_of :ics_file, :message=>': This ics file has already been used. (by you or someone else)'

    
    has_many :script_created_issues, :foreign_key => 'user_calendar_id', :dependent => :delete_all
   
   #this needs to be set up later
   # has_many :processed_results, :foreign_key => 'user_calendar_id', :dependent => :delete_all
   
   User.class_eval do
     has_many :user_calendars
   end
end

app/controllers/user_calendars_controller.rb
# Calendar Importer - plugin for redmine project management software
# Copyright (C) 2007-2012  Blend Interactive
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class UserCalendarsController < ApplicationController
  unloadable
  layout 'base'

  def just_user_calendars
    @user = User.find(params[:user_id])
    render :partial=>"calendar_imports/user_calendar_list", :locals=>{:user_calendars=>@user.user_calendars}
  end

  # GET /user_calendars
  # GET /user_calendars.xml
  def index
    @user_calendars = UserCalendar.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @user_calendars }
    end
  end

  # GET /user_calendars/1
  # GET /user_calendars/1.xml
  def show
    @user_calendar = UserCalendar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user_calendar }
    end
  end

  # GET /user_calendars/new
  # GET /user_calendars/new.xml
  def new
    @user_calendar = UserCalendar.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user_calendar }
    end
  end

  # GET /user_calendars/1/edit
  def edit
    @user_calendar = UserCalendar.find(params[:id])
    
  end

  # POST /user_calendars
  # POST /user_calendars.xml
  def create
    @user_calendar = UserCalendar.new(params[:user_calendar])

    respond_to do |format|
      if @user_calendar.save
        format.html { redirect_to (url_for :controller => "calendar_imports", :action => "index"), notice: "The calendar '#{@user_calendar.name}' was successfully created." }
        format.json { render json: @user_calendar, status: :created, location: @user_calendar }
      else
        @user = User.current
        format.html { render "new" }
        format.json { render json: @user_calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_calendars/1
  # PUT /user_calendars/1.xml
  def update
    @user_calendar = UserCalendar.find(params[:id])

    respond_to do |format|
      if @user_calendar.update_attributes(params[:user_calendar])
        flash[:notice] = "'#{@user_calendar.name}' was successfully updated."
        format.html { redirect_to(calendar_import_path) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user_calendar.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_calendars/1
  # DELETE /user_calendars/1.xml
  def destroy
    unless params[:id]
      raise "No ID passed"
    end
    puts params[:id]

    @user_calendar = UserCalendar.find(params[:id])
    @name = @user_calendar.name
    @user_calendar.destroy
    respond_to do |format|
      flash[:notice] = "The calendar '#{@name}' was successfully removed."
      format.html { redirect_to(url_for :controller => "calendar_imports", :action => "index") }
      format.xml  { head :ok }
    end
  end
end

app/views/user_calendars/edit.html.erb
<h1>Edit Calendar Name</h1>

<%= error_messages_for @user_calendar %>

<%= form_for(@user_calendar) do |f| %>
  <%= f.hidden_field :user_id, :value => @user_calendar.user_id %>
  <p>
    <b>Calendar Name</b><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <b>Ics file</b><br />
    <%= @user_calendar.ics_file %>
  </p>
  
  <p>
    <%= f.submit "Update"%>
  </p>
<% end %>

<%= link_to 'Show', show_user_calendar_path %> |
<%= link_to 'Back', calendar_import_path %>

app/views/user_calendars/index.html.erb
<h1>Listing user_calendars</h1>

<table>
  <tr>
    <th>User</th>
    <th>Ics file</th>
  </tr>

<% for user_calendar in @user_calendars %>
  <tr>
    <td><%=h user_calendar.user_id %></td>
    <td><%=h user_calendar.ics_file %></td>
    <td><%= link_to 'Show', :controller => "user_calendar", :id => user_calendar %></td>
    <td><%= link_to 'Edit', :controller => "user_calendar", :id => user_calendar, :method => :edit%></td>
    <td><%= link_to 'Destroy', :controller => "user_calendar", :id => user_calendar, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New user_calendar', :controller => "user_calendars", :action => "new" %>

app/views/user_calendars/new.html.erb
<h1>New Calendar</h1>

<%= error_messages_for @user_calendar %>

<%= form_for(@user_calendar) do |f| %>
    <%= f.hidden_field :user_id %>

  
  <p>
    <b>Calendar Name</b><br />
    <%= f.text_field :name, :autofocus => true %></td>
  </p>
    

  <p>
    <b>Ics file</b><br />
    <%= f.text_field :ics_file %>
  </p>

  <p>
    <b>HTTP User</b><br />
    <%= f.text_field :http_user %>
  </p>

  <p>
    <b>HTTP Password</b><br />
    <%= f.text_field :http_password %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', :controller=>'calendar_imports', :action=>'index' %>

app/views/user_calendars/show.html.erb
<h1>User Calendar Details</h1>
<p>
  <b>Calendar Name:</b>
  <%=h @user_calendar.name %>
</p>

<p>
  <b>ICS file:</b>
  <%=h @user_calendar.ics_file %>
</p>

<p>
  <b>HTTP User:</b>
  <%=h @user_calendar.http_user %>
</p>

<%= link_to 'Edit Calendar Name', edit_user_calendar_path %> |
<%= link_to 'Back', calendar_import_path %>