config/routes.rb
# Calendar Importer - plugin for redmine project management software
# Copyright (C) 2007-2012  Blend Interactive
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


RedmineApp::Application.routes.draw do
  match 'calendar_import/:name' => 'calendar_imports#user_index'
  match 'calendar_import/:name/pull' => 'calendar_imports#user_pull'
  match 'calendar_import' => 'calendar_imports#index'
  
  match 'user_calendars/show/:id' => 'user_calendars#show', :as => "show_user_calendar", :via => :get
  match 'skipped_entries/show/:id' => 'skipped_entries#show', :as => "show_skipped_entries", :via => :get  
  
  resources :user_calendars
  resources :user_to_project_mappings
  resources :event_to_issue_errors
  #resources :skipped_entries
end

app/controllers/calendar_imports_controller.rb
# Calendar Importer - plugin for redmine project management software
# Copyright (C) 2007-2012  Blend Interactive
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class CalendarImportsController < ApplicationController
  unloadable
  layout 'base'

  def index
    @user = User.current
    @user_calendar = UserCalendar.new
    @errors = Error.find(:all)
    #UserToProjectMapping.find(@user.id)
  end

  def user_index
  	#TODO restrict this to admins
  	split = params[:name].split(',')
  	firstname = split[0]
  	lastname = split[1]
  	@user = User.find_by_firstname_and_lastname(firstname,lastname)
  	@user_calendar = UserCalendar.new
  	
  	render "index"
  end

  def user_pull
    split = params[:name].split(',')
    firstname = split[0]
    lastname = split[1]
    @user = User.find_by_firstname_and_lastname(firstname,lastname)
    ImportProcessor::process_user(@user)
    @user_calendar = UserCalendar.new

    render 'index'
  end
end

app/views/calendar_imports/_event_to_issue_errors_list.html.erb
<% if event_to_issue_errors.any? %>
<div class="flash error">You'll need to resolve these errors by editing your calendar entries through the system you used to enter them.  The details on this page will help you find the items you are looking for.</div>

<table class="list">
<thead>
  <tr>
    <th>Project</th>
    <th>Error</th>
    <th></th>
  </tr>
</thead>

<% for event_to_issue_error in event_to_issue_errors %>
  <tr title="Date: <%=h event_to_issue_error.start_date.strftime('%m-%d-%Y %I:%M:%S %p %Z') %>" >
    <td><%=h event_to_issue_error.summary %></td>
    <td><%=h error[event_to_issue_error.error_id-1].description %></td>
    <td width="60px"><%= link_to 'See Details', event_to_issue_error %></td>
  </tr>
<% end %>
</table>
<p></p>

<% else %>
<div class="flash notice">No Errors!</div>
<% end %>

app/views/calendar_imports/_new_user_calendar.html.erb
<br />


<%= form_for(@user_calendar) do |f| %>
    <%= f.hidden_field :user_id, :value => @user.id %>


<table>
    <tr>
        <td>
            <b>Calendar Name</b><br />
            <%= f.text_field :name %></td>
        <td>
            <b>ICS File URL</b><br />
            <%= f.text_field :ics_file %></td>
    </tr>
    <tr>
        <td>
            <b>HTTP User</b><br />
            <%= f.text_field :http_user %></td>
        <td>
            <b>HTTP Password</b><br />
            <%= f.text_field :http_password %></td>
    </tr>
</table>

  <p>
    <%= f.submit "Add" %>
  </p>
<% end %>

app/views/calendar_imports/_skipped_entries_list.html.erb
<% if skipped_entries.any? %>

<div class="box">
<h3>Skipped Time Entries</h3>
    
    <table class="list">
    <thead>
          <tr>
            <th>Project</th>
            <th>Date</th>
            <th></th>
          </tr>
    </thead>
    <% for skipped_entry in skipped_entries %>
      <tr title="<%=h skipped_entry.skipped_text %>" >
        <td><%=h skipped_entry.summary %></td>
        <td><%=h skipped_entry.start_date.strftime('%m/%d/%y %I:%M:%S %p %Z') %></td>
        <td><%= link_to 'See Details', show_skipped_entries_path(skipped_entry) %></td>
      </tr>
    <% end %>
    
    </table>
</div>

<% end %>

app/views/calendar_imports/_user_calendar_list.html.erb
<div id="user_calendars">
    <table class="list">
    <thead>
      <tr>
        <th>Calendar Name</th>
        <th>ICS File URL</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <% for user_calendar in user_calendars %>
      <tr title="<%=h user_calendar.ics_file %>">
        <td><%= link_to user_calendar.name, edit_user_calendar_path(user_calendar) %></td>
        <td>
            <% unless user_calendar.ics_file.slice(-30,30).nil? %>
                <%=h '...'+user_calendar.ics_file.slice(-30,30) %>
            <% end %>
        </td>
        
        <td><%= link_to 'Show', :controller => "user_calendars", :id => user_calendar, :action => "show" %></td>
        <td><%= link_to 'Delete', "user_calendars/#{user_calendar.id}", :id => user_calendar, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
      </tr>
    <% end %>
    </table>

</div>

app/views/calendar_imports/_user_to_project_mappings_list.html.erb
<% if user_to_project_mappings.any? %>

    <table class="list">
    <thead>
      <tr>
        <th>Project</th>
        <th>Project alias</th>
        <th>Single Event</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <% for user_to_project_mapping in user_to_project_mappings %>
        <% if Project.exists?(user_to_project_mapping.project_id) %>
            <tr>
            <td><%=h Project.find(user_to_project_mapping.project_id).name %></td>
            <td><%=h user_to_project_mapping.project_alias %></td>
            <td><% if !user_to_project_mapping.event_guid.nil?
                        if user_to_project_mapping.event_guid!=''%>
                
                        X
                <%      end
                    end %></td>
            <td><%= link_to 'Edit', edit_user_to_project_mapping_path(user_to_project_mapping) %></td>
            <td><%= link_to 'Remove', user_to_project_mapping_path(user_to_project_mapping), :confirm => 'Are you sure?', :method => :delete %></td>
            </tr>
        <% else %>
         <tr style="background-color: #FFE3E3;" >
            <td>INVALID MAPPING!</td>
            <td><%=h user_to_project_mapping.project_alias %></td>
            <td></td>
            <td></td>
            <td><%= link_to 'Remove', user_to_project_mapping, :confirm => 'Are you sure?', :method => :delete %></td>
         </tr>
        <% end %>
    <% end %>
    </table>
<% else %>
    <div>You currently don't have any projects aliased.</div>
<% end %>

    <%= link_to 'Create a New Alias', new_user_to_project_mapping_path %>
    

app/views/calendar_imports/index.html.erb
<h2>Calendar Import</h2>

<div class="splitcontentleft">

    
    <% if @user != nil %>
        <div class="box">
        <h3>Calendars</h3>
        <%= render :partial=>"user_calendar_list", :locals => {:user_calendars => @user.user_calendars} %>
        <%= render :partial=>'new_user_calendar', :locals => {:user_calendar => UserCalendar.new()} %>
        </div>
    <% end %>

     <div class="box">
        <h3>Project Aliases</h3>
            <%= render :partial=>"user_to_project_mappings_list", :locals => { :user_to_project_mappings => @user.user_to_project_mappings} %>
        </div>

</div>

<div class="splitcontentright">

        <div class="box">
        <h3>Import Errors</h3>
            <%= render :partial=>"event_to_issue_errors_list", :locals => {:event_to_issue_errors => @user.event_to_issue_errors.find(:all, :conditions => ["start_date > ?", 2.months.ago ]), :error => @errors} %>
        </div>
        
        <%= render :partial=>"skipped_entries_list", :locals => {:skipped_entries=>@user.skipped_entries.find(:all, :conditions => ["start_date > ?", 2.months.ago ])} %>
</div>  